@startuml
skinparam shadowing false
skinparam monochrome true
skinparam classAttributeIconSize 0
hide circles

skinparam class {
BackgroundColor white
}

Communicator <.. AgentMessage
Communicator <.. GMMessage
Communicator *-right-"1" ISender

class Communicator {
- correlation: Dictionary<int, Descriptor>
- GMDescriptor: Descriptor
- messageService: ISender
+ SendMessageToAgent(GMMessage)
+ SendMessageToGM(AgentMessage)
}

class AgentMessage {
+ payload: string
}

class GMMessage {
+ id: int
+ payload: string
}

interface ISender  <<interface>> {
+ SendMessage()
}
@enduml
