@startuml
skinparam shadowing false
skinparam monochrome true
skinparam classAttributeIconSize 0
hide circles

skinparam class {
BackgroundColor white
}

IStrategy <|.. Strategy
Player *-- "4..*" Field
Player *-- "1" IStrategy
Player *-- "1" Team
Player *-- "1" GoalInfo

class Player {
- id: int
+ delayTime: int
+ penaltyTime: int
+ team: Team
+ isLeader: bool
+ havePiece: bool
+ board Field[,]
+ position: Tuple<int, int>
+ waitingPlayers: List<Tuple<int, bool>>
- strategy: IStrategy
+ teamMates: int[]

+ Player()
+ JoinTheGame()
+ Start()
+ Stop()
+ Move()
+ PickUp()
+ Put()
+ BegForInfo()
+ GiveInfo()
+ RequestsResponse()
+ CheckPiece()
+ AcceptMessage()
+ MakeDecisionFromStrategy()
- Communicate()
- Penalty()
}

class Field{
+ goalInfo: GoalInfo
+ playerInfo: bool
+ distToPiece: int
}

interface IStrategy <<interface>> {
+ MakeDecision()
}

class Strategy {
+ MakeDecision()
}

enum Team <<enumeration>> {
Red
Blue
}

enum GoalInfo <<enumeration>> {
IDK
GoalInfoDiscovered
DiscoveredNotGoal
DiscoveredGoal
}
@enduml
