@startuml
skinparam shadowing false
skinparam monochrome true
skinparam classAttributeIconSize 0
hide circles

skinparam class {
BackgroundColor white
}

IStrategy <|.. Strategy
Player *-- Field
Player -- "1" IStrategy

class Player {
- id: int
+ delay: int
+ team: Team
+ isLeader: bool
+ havePiece: bool
+ board Field[,]
+ position: Tuple<int, int>
+ waitingPlayers: List<Tuple<int, bool>>
- strategy: IStrategy
+ teamMates: int[]

+ Player()
+ Move()
+ PickUp()
+ Put()
+ BegForInfo()
+ GiveInfo()
+ RequestsResponse()
+ CheckPiece()
+ GetInfoFromGM()
+ MakeDecisionFromStrategy()
- Communicate()
}

class Field{
+ goalInfo: GoalInfo
+ playerInfo: bool
+ distToPiece: int
}

interface IStrategy <<interface>> {
+ MakeDecision()
}

class Strategy {
+ MakeDecision()
}

enum Team <<enumeration>> {
Red
Blue
}

enum GoalInfo <<enumeration>> {
IDK
GoalInfoDiscovered
DiscoveredNotGoal
DiscoveredGoal
}
@enduml
