@startuml
skinparam shadowing false
skinparam monochrome true
skinparam classAttributeIconSize 0
hide circles

skinparam class {
BackgroundColor white
}

IStrategy <|.. Strategy
Player *-- "4..*" Field
Player *-- "1" IStrategy
Player *-- "1" ISender
Player ..> GoalInfo
Player ..> Team

class Player {
- id: int
- sender: ISender
+ penaltyTime: int
+ team: Team
+ isLeader: bool
+ havePiece: bool
+ board Field[,]
+ position: Tuple<int, int>
+ waitingPlayers: List<int>
- strategy: IStrategy
+ teamMates: int[]

+ Player()
+ JoinTheGame()
+ Start()
+ Stop()
+ Move()
+ Put()
+ BegForInfo()
+ GiveInfo()
+ RequestsResponse()
+ CheckPiece()
+ AcceptMessage()
+ MakeDecisionFromStrategy()
- Communicate()
- Penalty()
}

class Field{
+ goalInfo: GoalInfo
+ playerInfo: bool
+ distToPiece: int
}

interface IStrategy <<interface>> {
+ MakeDecision()
}

interface ISender <<interface>> {
+ SendMessage()
}


class Strategy {
+ MakeDecision()
}

enum Team <<enumeration>> {
Red
Blue
}

enum GoalInfo <<enumeration>> {
IDK
DiscoveredNotGoal
DiscoveredGoal
}
@enduml
