@startuml
skinparam shadowing false
skinparam monochrome true
hide empty description

title Cel

[*] -> Pusty : start
Pusty -> MaAgenta : wejście agenta
Pusty -> [*] : koniec

MaAgenta -> MaFragment : przyjęcie fragmentu
MaFragment -> MaAgenta : wejście agenta
MaAgenta --> Pusty : zejście bez sukcesu

MaFragment -> [*] : koniec
@enduml