@startuml
skinparam shadowing false
skinparam monochrome true
hide empty description

title Cel

state "Pusty" as pusty
state "Ma Agenta" as maAgenta
state "Ma Fragment" as maFragment
state "Ma agenta i fragment" as maif

[*] -> pusty : start
pusty -down-> maAgenta : wejście agenta
pusty -> [*] : koniec

maAgenta -right-> maif : przyjęcie fragmentu
maAgenta -> pusty : zejście agenta

maFragment -up-> maif : wejście agenta
maif -down-> maFragment : zejście agenta
maif -right-> [*] : koniec
maFragment --> [*] : koniec
@enduml
