@startuml
skinparam shadowing false
skinparam monochrome true
hide empty description
title Fragment
[*] -> Aktywny : wygenerowanie
Aktywny --> Podniesiony : podniesienie

Podniesiony --> Położony : położenie
Podniesiony --> [*] : zniszczenie


Położony --> [*] : pole bramkowe
Położony --> Aktywny : pole zadań
Położony : entry/ sprawdź pole
Położony : exit/ zwróć informacje
@enduml
